yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание записи
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    # Подписки и отписки
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='post')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

LENGTH_TEXT = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name='Описание',
                                   blank=True, null=True)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(verbose_name="Комментарий",
                            help_text="Ваш комментарий")
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Время и дата публикации",
        db_index=True

    )

    def __str__(self):
        return self.text[:LENGTH_TEXT]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Имя автора'
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Выбор группы для поста',
            'image': 'Загрузите изображение'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': ('Текст комментария'),
        }
        text_help = {
            'text': ('Текст комментария'),
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow

AMOUNT_POST = 10


def page_context(request, posts):
    """Паджинатор."""
    paginator = Paginator(posts, AMOUNT_POST)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20)
def index(request):
    """Функция для отображения главной страницы проекта."""
    template = 'posts/index.html'
    post_list = Post.objects.select_related("group").all()
    page_obj = page_context(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Функция для отображения страницы сообщества."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    groups_posts = group.posts.select_related('author')
    page_obj = page_context(request, groups_posts)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    """Функция для отображения профиля пользователя."""
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group')
    page_obj = page_context(request, post_list)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    else:
        following = False
    context = {
        'author': author,
        'following': following,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Функция для отображения конкретной записи."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post.objects.select_related('group'), id=post_id)
    comments = post.comments.select_related('post')
    context = {
        'post': post,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Функция для создания записи."""
    template = 'posts/create_post.html'
    post = Post.objects.select_related('author')
    form = PostForm(request.POST or None, request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('post:profile', post.author.username)
    context = {
        'post': post,
        'form': form,
    }

    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """Функция для редактирования записи."""
    template = 'posts/create_post.html'
    edit_post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=edit_post
                    )

    if edit_post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)

    context = {
        'post_id': post_id,
        'form': form,
        'is_edit': True
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """Функция для добавления комментария."""
    template = 'posts/post_detail.html'
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.select_related('post')
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, template, context)


@login_required
def follow_index(request):
    """Подписка на пользователя."""
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = page_context(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Функция для подписки на автора."""
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Функция для отписки от автора."""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
{% if is_edit %}
  Редактировать пост
  {% else %}
  Создать новый пост
  {% endif %}
{% endblock title %}

{% block content %}
{% load user_filters %}
  <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
            {% if is_edit %}
            Редактировать пост
            {% else %}
            Создать новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          {% if is_edit %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id %}"
          {% else %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}"
          {% endif %}          >
            {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}>
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
  Избранные авторы
{% endblock title %}

{% block content %}
  {% load thumbnail %}
    <div class="container py-5">
      {% include 'includes/switcher.html' %}
      <h1>Последние обновления у избранных авторов</h1>
      {% for post in page_obj %}
        {% include 'includes/post_card.html' with display_group_link=True %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Записи сообщества {{ group.title }}
{% endblock title %}

{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
      <p>
        {{ group.description|linebreaksbr }}
      </p>
    {% for post in page_obj %}
      {% include 'includes/posts.html' %}
        <p>{{ post.text|linebreaks }}</p>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
    {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}
Последние обновления на сайте
{% endblock title %}

{% block content %}
  {% load thumbnail %}
    <div class="container py-5">
    {% include 'includes/switcher.html' %}
    {% cache 20 index_page page_obj.number %}
    {% for post in page_obj %}
    {% include 'includes/posts.html' %}
      <p>{{ post.text|linebreaks }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
      <a href="{% url 'posts:post_detail' post.pk %}">
        Подробная информация
      </a>
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
      {% endif %}
      {% if post.author == user %}
      <a href="{% url 'posts:post_edit' post.pk %}">
        Редактировать запись
      </a>
       {% endif %}
       {% if not forloop.last %}<hr>{% endif %}
       {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </div>
    {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  Пост {{ post.text|truncatechars:30}}
{% endblock title %}

{% block content %}
{% load thumbnail %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li class="list-group-item">
          Группа: {{ post.group.title }}, {{ post.group.description|linebreaksbr }}
          {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            Все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a>
        </li>
        <li>
          {% if post.author == user %}
           <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
             Редактировать запись
           </a>
          {% endif %}
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
      {{ post.text|linebreaks}}
      </p>
      {% include 'posts/includes/comments.html'%}
  </article>
</div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
Профайл пользователя {{ author.get_full_name }}
{% endblock title %}

{% block content %}
{% load thumbnail %}
    <div class="mb-5">
    <h1>Персональная станица пользователя {{ author.get_full_name }}</h1>
    <h3>Всего у пользователя постов: {{ author.posts.count }} </h3>
    <h3>Всего подписчиков: {{ author.following.count }}</h3>
    {% if request.user != author %}
        {% if following %}
          <a class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}"
            role="button">Отписаться</a>
        {% else %}
          <a class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}"
            role="button">Подписаться</a>
        {% endif %}
    {% endif %}
    </div>
    {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}